fix: remove regex to test the access token format
VilledeMontreal/node-jwt-validator pull request #14
Opened 2024-05-30 19:43 UTC by lawp09

Due to the authentification migration, the format of the access token is not anymore uuid. So to the tokenTransformationMiddleware works we need to remove the regex format check.
The access token can have other format like JWT or uuid now.

2024-05-30 20:07 UTC, lawp09 commented
@livetocode

2024-05-31 14:31 UTC, livetocode requested changes

2024-05-31 14:31 UTC, livetocode commented on src/middleware/tokenTransformationMiddleware.ts
> +      const accessTokenRegExpArray = authHeader.split(' ');
peux-tu renommer accessTokenRegExpArray en accessTokenSegments pour éviter la confusion avec l'ancien RegEx?

2024-05-31 15:10 UTC, lawp09 commented on src/middleware/tokenTransformationMiddleware.ts
> +      const accessTokenRegExpArray = authHeader.split(' ');
C'est fait

2024-05-31 17:56 UTC, livetocode commented on src/middleware/tokenTransformationMiddleware.ts
> +      const accessToken = accessTokenSegments[1];
Je réalise qu'en faisant ce changement, cela brise le comportement précédant avec les tokens de Gluu qui ne sont pas au format JWT et qui n'ont pas de point.
Dans ce cas, prendre le segment du milieu retournera undefined comme access token!
Par ailleurs, le header Authorization contient aussi le préfixe "Bearer " qui n'est plus enlevé!
Donc j'ai des gros doutes sur le fonctionnement correct du middleware suite à ce changement!

2024-05-31 18:01 UTC, livetocode commented on src/middleware/tokenTransformationMiddleware.ts
> +      const accessToken = accessTokenSegments[1];
Je crois qu'on pourrait en fait revoir le regex pour tout simplement extraire le texte après "Bearer ".

2024-05-31 19:49 UTC, lawp09 commented on src/middleware/tokenTransformationMiddleware.ts
> +      const accessToken = accessTokenSegments[1];
![Capture d’écran, le 2024-05-31 à 15 43 24](https://github.com/VilledeMontreal/node-jwt-validator/assets/20357989/47435757-528e-4170-9c4e-a08fe7cdad14)

En testant sur mon local tout à l'air de fonctionner avec Gluu et un heared Authorization `Bearer b72917ee-9012-489e-be8d-6710008da50f`. La variable accessToken ne contient plus que `b72917ee-9012-489e-be8d-6710008da50f` et l'appel subséquent vers la route `/api/security/v1/token-translator` me retourne bien un JWT.

Je vais refaire des tests la semaine prochaine pour confirmer.

2024-06-03 22:05 UTC, livetocode approved these changes
Merci pour les derniers changements, c'est très clean!

2024-06-03 22:05 UTC, merged